"""add streak fields and todo completed_at

Revision ID: beb986319dba
Revises: 9dc422eab556
Create Date: 2026-07-19 17:44:44.424423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'beb986319dba'
down_revision: Union[str, Sequence[str], None] = '9dc422eab556'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('completed_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('streak_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('users', sa.Column('last_published_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_published_date')
    op.drop_column('users', 'streak_count')
    op.drop_column('todos', 'completed_at')
    # ### end Alembic commands ###
